### ISSUE TITLE
some issue with scripcode = 35094

### ISSUE THREAD

**Issue by vinayakbhovi** [5paisa/py5paisa#126]
only this particular script code does not work and others are working fine  35094

df = client.historical_data('N','D',35094,'5m','2022-01-10','2022-01-17')
print(df)

it gives a following error

Traceback (most recent call last):
  File "c:\Users\vinay\Desktop\function tester\1login.py", line 39, in <module>
    dft = type(client.historical_data('N','D',35094,'5m','2022-01-10','2022-01-17'))
  File "C:\Python39\lib\site-packages\py5paisa\py5paisa.py", line 422, in historical_data
    df.columns=['Datetime','Open','High','Low','Close','Volume']
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Python39\lib\site-packages\pandas\core\generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Python39\lib\site-packages\pandas\core\internals\managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Python39\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 6 elements
PS C:\Users\vinay\Desktop\function tester>

i think  that it is not sending any data or returning null.

**Comment by 5paisa** [comment]
Hi @vinayakbhovi ,

Can you confirm if the contract you tried fetching data was expired?
