### ISSUE TITLE
Unable to login. Exception: Please configure your keys in keys.conf

### ISSUE THREAD

**Issue by kumarchinmaya116** [5paisa/py5paisa#50]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

The first time I tried to login, it showed a logged in!! message. But thereafter, I am not able to login. every time i run the script, I get the error: Exception: Please configure your keys in keys.conf.
I have saved my keys in keys.conf file as per the instruction and saved the file in the directory where i have kept the script. Still it shows the same error.

### What I Did

```
from py5paisa import FivePaisaClient
client = FivePaisaClient(email="k*****************6@gmail.com", passwd="***********", dob="********")
client.login()
( in place of * i have used my credentials)

The output:
Traceback (most recent call last):

  File "C:\Users\dhriti\Anaconda3\envs\trading\lib\site-packages\py5paisa\conf.py", line 9, in <module>
    section = config["KEYS"]

  File "C:\Users\dhriti\Anaconda3\envs\trading\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)

KeyError: 'KEYS'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-7999cee77a8c>", line 1, in <module>
    from py5paisa import FivePaisaClient

  File "C:\Users\dhriti\Anaconda3\envs\trading\lib\site-packages\py5paisa\__init__.py", line 1, in <module>
    from py5paisa.py5paisa import FivePaisaClient

  File "C:\Users\dhriti\Anaconda3\envs\trading\lib\site-packages\py5paisa\py5paisa.py", line 2, in <module>
    from .auth import EncryptionClient

  File "C:\Users\dhriti\Anaconda3\envs\trading\lib\site-packages\py5paisa\auth.py", line 8, in <module>
    from .conf import ENCRYPTION_KEY

  File "C:\Users\dhriti\Anaconda3\envs\trading\lib\site-packages\py5paisa\conf.py", line 11, in <module>
    raise Exception("Please configure your keys in keys.conf")

Exception: Please configure your keys in keys.conf
```
Has anyone faced similar issue? If so, what can be done?

Regards
Chinmaya

**Comment by coder-amogh** [comment]
Did you read [this](https://5paisa.github.io/usage/auth/)?
Did you try to run through command line? I think the working directory should be the same as where the file is stored.

**Comment by pawarvijay** [comment]
@coder-amogh @kumarchinmaya116 

the api keys link is wrong in documentation
i have raised MR for it Here https://github.com/5paisa/py5paisa/pull/58

**Comment by bpsrinivas** [comment]
File "C:\Users\pbalakr3\IdeaProjects\PythonProjects\src\stockanalysis\5paisa\broker.py", line 1, in <module>
    from py5paisa import FivePaisaClient
  File "C:\Users\pbalakr3\IdeaProjects\PythonProjects\venv\lib\site-packages\py5paisa\__init__.py", line 1, in <module>
    from py5paisa.py5paisa import FivePaisaClient
  File "C:\Users\pbalakr3\IdeaProjects\PythonProjects\venv\lib\site-packages\py5paisa\py5paisa.py", line 3, in <module>
    from .auth import EncryptionClient
  File "C:\Users\pbalakr3\IdeaProjects\PythonProjects\venv\lib\site-packages\py5paisa\auth.py", line 8, in <module>
    from .conf import ENCRYPTION_KEY
  File "C:\Users\pbalakr3\IdeaProjects\PythonProjects\venv\lib\site-packages\py5paisa\conf.py", line 11, in <module>
    raise Exception("Please configure your keys in keys.conf")
Exception: Please configure your keys in keys.conf




sometimes it works .. then it stops working ...

**Comment by premagrawal** [comment]
No Keys.conf file found in the directory, when I create keys.conf fille it throws another JWToken Error

**Comment by Dhruvt75** [comment]
i have also same problem can anyone solve this

**Comment by Parthiban-Sampath** [comment]
First, check the working directory of your program.
In the same directory, create keys.conf file with the same format as in https://github.com/5paisa/py5paisa.
Then try login.
