### ISSUE TITLE
Issue while using encrypted key

### ISSUE THREAD

**Issue by jegan1994** [5paisa/py5paisa#52]
* 5paisa Python SDK version: 0.2.1
* Python version: Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
* Operating System: Windows 10

### Description

While using code with email id, password and DOB as plain text the program works fine. But while using encrypted form, the Program fails. PFB errors.

### output (Errors - Runtime)
Traceback (most recent call last):
  File "C:\...\xxx.py", line 5, in <module>
    client.login()
  File "C:\...\Python\Python39\lib\site-packages\py5paisa\py5paisa.py", line 56, in login
    res = self._login_request(self.LOGIN_ROUTE)
  File "C:\...\Python\Python39\lib\site-packages\py5paisa\py5paisa.py", line 79, in _login_request
    return res.json()
  File "C:\...\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\...\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\...\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\...\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks.

**Comment by rishabhmaniyar** [comment]
Hey @jegan1994 ,
It is getting encrypted automatically by our SDK.
So you can enter regular credentials and try logging into again!

**Comment by jegan1994** [comment]
Thanks Rishab
