### ISSUE TITLE
historical data error

### ISSUE THREAD

**Issue by Rahulghuge94** [5paisa/py5paisa#78]
hello im getting the erroer while running the client.historical_data('N','D',53179,'1m',20210701','20210703')
 everything is ok.but server is not returning data so it is theowing error. can you  please solve that error if it is internal. or may be packege needed to upgrade.

>>> client.historical_data('N','D',53179,"1m",'20210701','20210703')
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    client.historical_data('N','D',53179,"1m",'20210701','20210703')
  File "C:\Users\win10\AppData\Local\Programs\Python\Python39\lib\site-packages\py5paisa\py5paisa.py", line 369, in historical_data
    df.columns=['Datetime','Open','High','Low','Close','Volume']
  File "C:\Users\win10\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\win10\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\win10\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 6 elements

**Comment by 5paisa** [comment]
Hi @Rahulghuge94 ,

Please request for data less than 6 months to get the historical data successfully.

**Comment by qalpesh** [comment]
pls provide the code for reference for troubleshooting. However from the error it seems program is client.historical_data is returning dataframe and pandas is throwing error on columns processing. Though I may be wrong.
